services:
  gitsync:
    build: .
    command:
      - -ssh
      - -repo=git@github.com:medblocks/aarthy-migrations.git
      - -root=/tmp/git/root
      - -wait=120
      - -ssh-key-file=/etc/git-secret/ssh
      - -ssh-known-hosts-file=/etc/git-secret/known_hosts
      - -timeout=1000
      - -v=20
    volumes:
      - ./secret:/etc/git-secret
      - ./clone:/tmp/git